[flang][cuda] Copy type descriptor used in fir.alloca op (#184859)
Avoid error like:

```
error: runtime derived type info descriptor was not generated
```

(cherry picked from commit 520319e3e0d2c22fd462a72583f88977bb882ca3)