[clang][ssaf][NFC] Avoid incomplete EntitySummary type breakage (#182946)
When parsing LUSummary.h as a standalone header unit, EntitySummary is
an incomplete type, causing compilation to fail:

```
__memory/unique_ptr.h:72:19: error: invalid application of 'sizeof' to an incomplete type 'clang::ssaf::EntitySummary'
   72 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
...
clang/include/clang/Analysis/Scalable/EntityLinker/LUSummary.h:48:12: note: in instantiation of member function 'std::map<clang::ssaf::SummaryName, std::map<clang::ssaf::EntityId, std::unique_ptr<clang::ssaf::EntitySummary>>>::map' requested here
   48 |   explicit LUSummary(NestedBuildNamespace LUNamespace)
      |            ^
clang/include/clang/Analysis/Scalable/EntityLinker/LUSummary.h:27:7: note: forward declaration of 'clang::ssaf::EntitySummary'
   27 | class EntitySummary;
```

This is not a total breakage because this header file builds
successfully when used in a .cpp file that includes EntitySummary.h
prior to this.

See https://llvm.org/docs/CodingStandards.html#self-contained-headers

(cherry picked from commit df128ce63e8d7abce77ce0e1cd388ade0f21e501)