[CodeGen] Silence a warning (NFC)
llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:4665:12:
 error: unused variable 'NumElts' [-Werror,-Wunused-variable]
  unsigned NumElts = DemandedElts.getBitWidth();
           ^
1 error generated.

(cherry picked from commit 7806a0b699acc654844d0332283d6370d47bb689)