[lldb] cast char8_t* to char* to allow std::string construction under C++20 (#181928)
After 5d5301dc0c, lldb fails to compile under C++20 with:

```
llvm-project/lldb/source/Target/StackFrameList.cpp:975:12: error: no viable conversion from returned value of type 'const char8_t *' to function return type 'std::string' (aka 'basic_string<char>')
  975 |     return show_unicode_marker ? u8" * " : u8"* ";
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This PR reinterpret casts the unicode characters returned by
`GetFrameMarker` to `const char*`.

(cherry picked from commit 92ac31c34baa83d0718e70eb5590e16fc39cafc7)