[CMake] Disable PCH for targets with Objective-C srcs
Avoid Clang errors:

error: Objective-C was disabled in PCH file but is currently enabled
(cherry picked from commit 8c583bd4d1a943801f6a361d6c52c6b94617fcc6)