[clang][CodeGen] Avoid copy of loop variable (NFC)
/llvm-project/clang/lib/CodeGen/CodeGenPGO.cpp:1140:19: error: loop variable '[_, V]' creates a copy from type 'const value_type' (aka 'const llvm::detail::DenseMapPair<const clang::Stmt *, clang::CodeGen::CounterPair>') [-Werror,-Wrange-loop-construct]
  for (const auto [_, V] : *RegionCounterMap) {
                  ^
/llvm-project/clang/lib/CodeGen/CodeGenPGO.cpp:1140:8: note: use reference type 'const value_type &' (aka 'const llvm::detail::DenseMapPair<const clang::Stmt *, clang::CodeGen::CounterPair> &') to prevent copying
  for (const auto [_, V] : *RegionCounterMap) {
       ^~~~~~~~~~~~~~~~~~~
                  &
1 error generated.

(cherry picked from commit 5eccfaec2dc6d1d5d20c85cd680cf54fc49563d5)