[lldb] Fix compilation for 32 bit platforms
This fixes the following error on 32 bit platforms, if compiling with Clang:

    llvm-project/lldb/source/Utility/VirtualDataExtractor.cpp:211:55: error: non-constant-expression cannot be narrowed from type 'SizeType' (aka 'unsigned long long') to 'size_t' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
      211 |   return {m_start + static_cast<size_t>(entry->data), entry->size};
          |                                                       ^~~~~~~~~~~
    llvm-project/lldb/source/Utility/VirtualDataExtractor.cpp:211:55: note: insert an explicit cast to silence this issue
      211 |   return {m_start + static_cast<size_t>(entry->data), entry->size};
          |                                                       ^~~~~~~~~~~
          |                                                       static_cast<size_t>( )

(cherry picked from commit 865978a172d250b91a3dacbb16c10ff12b8800e6)