Fix riscv64gc_lp64d_nopic variant build error (#142)
While adding the riscv64gc_lp64d_nopic variant, the following build error was
observed.

In file included from
/local/mnt/workspace/actions-runner-2/_work/cpullvm-toolchain/cpullvm-toolchain/libunwind/src/Unwind-wasm.c:15:
/local/mnt/workspace/actions-runner-2/_work/cpullvm-toolchain/cpullvm-toolchain/libunwind/src/config.h:16:10:
fatal error: 'assert.h' file not found
   16 | #include <assert.h>
      |          ^~~~~~~~~~
1 error generated.

Adding -isystem fixes the error.

Signed-off-by: Pengxuan Zheng <pzheng@qti.qualcomm.com>
(cherry picked from commit 9cddb5c9316b861db71803010b040484b1bdc4b7)