[AMDGPU] Silence a warning (NFC)
llvm-project/llvm/lib/Target/AMDGPU/AMDGPURegBankLegalizeHelper.cpp:686:7:
 error: unused variable 'DstTy' [-Werror,-Wunused-variable]
  LLT DstTy = MRI.getType(Dst);
      ^
1 error generated.

(cherry picked from commit 11f64e92c627154a1caeb6d68c9999cca20f0dae)